language: node_js
node_js:
- 12.16.1
- 10.19.0
- 8.5.0
- 6.11.2
branches:
  only:
  - master
  - "/^v[0-9](\\.[0-9]+)(\\.[0-9]+)?$/"
script: npm run check
before_deploy: npm run build
deploy:
  provider: npm
  email: daniel.pazsoldan@gmail.com
  api_key:
    secure: mNWOPAlbEF4za/ETlkaWge2TI/rYm4UXC77Sc7fh5YVUMEDxe2VPPnBkIKgspDM9DCqyr0RPeZoGyKCRimfzoH3DBF1xv+6mc6ulbcwDiFpUOyDt/4dhQOtn67c9Ta8qZEHl0JGKPk8POp5AA0glKOKehrtSqUZ1HJw8FIg4C5WCs0Ad+2WkNfQsRCRfG6CBVJFYurhX1k8knslexsZNtyjkuP5TxAvwUDPcfvvxUVzcMkSGbxFl+rHdjS4SbQi4E8KwYajaWjCXNA3+N3xg2ed2V7Ba1MXMNloOYVnSKbyucIgGuLI6UE1UJX5B8MQDIRrcmqtyBRr4AnbfLPuwRtZJZUu+dTL1ihv+TJ9lGXPd47CS3oIZE0tjkxgzwZuLtCA8BCQCDVGWu+RwrobllGPirEoUsugddd/lz6AcQrZPbkrIcpLh216lQfMGZci7eggqohTSkWIIAFVMLCpkuy7aZBRzf+m5eem+a8Cidoin64tAM/QUApg2yNHPU7hMNBss7YpHcuxVKkZ9G9Djq8TSWlBHpCGvrjwZES0VoOPONyzVbFK3n8f8fSb46EFlkXPAyLz28jSVUQMYGgTanGPSIqCsvd+Pwpar/3UfjMJbjhZ27ub1ycrcCgbCZ+8bC2zzyBIJS0U1GW5XEBE9ULX6ImB2vTFwkjNNAV9zZeM=
  on:
    tags: true
    repo: danpaz/bodybuilder
    branch: master
    node: 10.19.0
